# Generated by Django 3.2.18 on 2023-03-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=201, verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Есть ответ?')),
                ('number_work', models.IntegerField(verbose_name='Лабораторная работа')),
                ('keywords1', models.CharField(max_length=200)),
                ('keywords', models.ManyToManyField(to='search.Keywords', verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['created_at'],
            },
        ),
    ]
