# Generated by Django 4.1.3 on 2022-11-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Ключевые слова')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Есть ответ?')),
                ('number_work', models.SmallIntegerField(verbose_name='Лабораторная работа')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['created_at'],
            },
        ),
    ]
