# Generated by Django 4.1.3 on 2022-11-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='number_work',
            field=models.IntegerField(verbose_name='Лабораторная работа'),
        ),
    ]
