# Generated by Django 4.1.3 on 2022-11-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_questions_number_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='number_work',
            field=models.IntegerField(blank=True, verbose_name='Лабораторная работа'),
        ),
    ]
